# Use container infrastructure.
sudo: false

install:
  - export ELLIESPATH="$TRAVIS_BUILD_DIR"
  - export PATH="$PATH:$ELLIESPATH/tools/linux/64-bit/bin"
  - tools/common/setup.bash

script:
  - goapp test ./api

after_success: |
  test "$TRAVIS_PULL_REQUEST" == "false" && \
  test "$TRAVIS_BRANCH" == "master" && \
  echo "$APPENGINE_PASSWORD" | \
    appcfg.py update ./api \ --email="$APPENGINE_EMAIL" --passin
