#!/usr/bin/env bash
set -x

# Don't lint changes that aren't being committed.
cd "$ELLIESPATH"
git stash save --keep-index --include-untracked 'Running pre-commit hook'

{
    # Go.
    golint ./api &&
    golint ./task &&

    # Web.
    cd "$ELLIESPATH/web" &&
    # TODO @daniel Figure out why `npm run gulp -- lint` doesn't work.
    npm run lint
}

# Exit with the same error code as the linters.
lint=${?}

# Return the working directory to its original state.
# See http://stackoverflow.com/questions/20479794/ for why we reset.
cd "$ELLIESPATH"
git reset --hard --quiet
git stash pop --index --quiet

exit ${lint}
