#!/usr/bin/env bash
set -x

# Don't lint changes that aren't being committed.
cd "$ELLIESPATH"
git stash save --keep-index --include-untracked

{
    # Go.
    golint ./api &&
    golint ./task &&

    # Web.
    cd "$ELLIESPATH/web" &&
    # TODO @daniel Figure out why `npm run gulp -- lint` doesn't work.
    npm run lint
}

# Return the working directory to its original state.
cd "$ELLIESPATH"
git stash pop --quiet
